const TYPES = {
    SET_USERS:'SET_USERS',
    FETCH_USERS:'FETCH_USERS',
    SET_LOADING_USER:'SET_LOADING_USER',
    CREATE_USER:'CREATE_USER',
    ADD_USER:'ADD_USER',
    UPDATE_USER:'UPDATE_USER',
    MODIFY_USER:'MODIFY_USER'
};

export default TYPES;